name: final_app_vision
description: "A new Flutter project."

# Prevent accidental publication to pub.dev
publish_to: 'none' # Remove this line if you want to publish to pub.dev

# Version and build number for the application.
version: 1.0.0+1

environment:
  sdk: ">=3.6.1 <4.0.0" # Specify the Dart SDK version range

dependencies:
  flutter:
    sdk: flutter

  # Add dependencies
  permission_handler: ^11.4.0
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  speech_to_text: ^7.0.0
  flutter_tts: ^4.2.2
  image_picker: ^1.1.2
  path_provider: ^2.1.5

  # Firebase dependencies (commented out)
  # firebase_core: ^3.12.1
  # firebase_storage: ^12.4.4
  
  # Custom dependencies
  firebase_data_connect: ^0.1.3+2
  cloudinary_flutter: ^1.3.0
  cloudinary_url_gen: ^1.7.0

  supabase_flutter: ^2.8.4
  geolocator: ^13.0.3
  mailer: ^6.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended linting for good coding practices
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Uncomment and modify to include your app's assets
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Uncomment and modify to include custom fonts
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
